//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayPyment
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatewayPayment
    {
        public int id_transaksi { get; set; }
        public Nullable<decimal> total { get; set; }
        public string no_kartu { get; set; }
        public string CVV { get; set; }
    }
}
